name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: sh ./build.sh
    - uses: actions/upload-artifact@v4
      with:
        name: Update_hotfix_universal
        path: build/Update_hotfix_universal.bin
