name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Remove old Kindletool
      run: rm -f ./utils/kindletool
    - name: Clone KindleTool
      uses: actions/checkout@v4
      with:
        repository: NiLuJe/KindleTool
        path: kindletool
    - name: Compile KindleTool
      run: |
          cd kindletool/
          sudo apt-get install -y zlib1g-dev libarchive-dev nettle-dev
          make
          mv KindleTool/Release/kindletool ./utils/kindletool
    - name: build
      run: |
          chmod 755 ./utils/kindletool
          chown -R $USER: ./utils/
          sh ./build.sh
    - uses: actions/upload-artifact@v4
      with:
        name: Update_hotfix_universal
        path: build/Update_hotfix_universal.bin
