name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  koxtoolchain:
    runs-on: ubuntu-latest

    steps:
    - name: Cache X-Tools
      id: cache-x-tools
      uses: actions/cache@v4
      with:
        path: ~/x-tools
        key: ${{ runner.os }}-x_tools
    - uses: actions/checkout@v4
      if: steps.cache-x-tools.outputs.cache-hit != 'true'
      with:
        repository: NiLuJe/koxtoolchain
    - name: Compile Toolcahin
      if: steps.cache-x-tools.outputs.cache-hit != 'true'
      run: |
          sudo apt-get install build-essential autoconf automake bison flex gawk libtool libtool-bin libncurses-dev curl file git gperf help2man texinfo unzip wget
          ./gen-tc.sh kindlepw2
          ./gen-tc.sh kindlehf
    - uses: actions/upload-artifact@v4
      with:
        name: koxtoolchain
        path: ~/x-tools

  kindletool:
    runs-on: ubuntu-latest

    steps:
    - name: Cache Kindletool
      id: cache-kindletool
      uses: actions/cache@v4
      with:
        path: KindleTool
        key: ${{ runner.os }}-kindletool
    - uses: actions/checkout@v4
      if: steps.cache-kindletool.outputs.cache-hit != 'true'
      with:
        repository: NiLuJe/KindleTool
    - name: Compile KindleTool
      if: steps.cache-kindletool.outputs.cache-hit != 'true'
      run: |
          sudo apt-get install -y zlib1g-dev libarchive-dev nettle-dev
          make
    - uses: actions/upload-artifact@v4
      with:
        name: kindletool
        path: KindleTool/Release/kindletool

  build:
    runs-on: ubuntu-latest
    needs: [kindletool, koxtoolchain]

    steps:
    - uses: actions/checkout@v4
    - name: Remove old Kindletool
      run: rm -f ./utils/kindletool
    - uses: actions/download-artifact@v4
      with:
        name: kindletool
        path: ./utils/
    - uses: actions/download-artifact@v4
      with:
        name: koxtoolchain
        path: ~/x-tools
    - name: Fix permissions
      run: |
          chown -R $USER: ~/x-tools/
          chmod -R a+rx ~/x-tools/
    - name: build
      run: |
          chmod 755 ./utils/kindletool
          chown -R $USER: ./utils/
          sh ./build.sh
    - uses: actions/upload-artifact@v4
      with:
        name: Update_hotfix_universal
        path: build/Update_hotfix_universal.bin